###
GET http://localhost:8080/Albums/
###
PATCH http://localhost:8080/Albums/1/song
Content-Type: application/json

{
        
  "title": "I Will Always Love You",
  "duration": "2.00",
  "comments": [
    "I wish it was never played again"
    ],
  "ratings": "1"
}

###
POST http://localhost:8080/Albums/
Content-Type: application/json

{

  "title": "The rigel axiom",
  "image": "urlHERE",
  "label": "music label",
  "comments": [],
  "songs": [],
  "ratings": "4"

}

###
PATCH http://localhost:8080/Albums/3/addsong
Content-Type: application/json

{
  "title": "the tristar",
  "duration": "04.00",
  "comments": [],
  "rating": "4 stars"
}

/// broken ///
###
DELETE http://localhost:8080/Albums/2/deletealbum 

###
DELETE http://localhost:8080/Albums/1/deletesong/5 
